### ISSUE TITLE
installer.sig file terminated with newline

### ISSUE THREAD

**Issue by Bilge** [composer/composer.github.io#2]
Since the `installer.sig` file is terminated with a newline, the following is `false`:

```php
file_get_contents('https://composer.github.io/installer.sig')) 
    === hash_file('sha384', 'composer-setup.php'); // false
```

In the [canonical example using `installer.sig`](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md), which is a shell script, the shell implicitly strips off the newline when the result of the subshell is captured. However, in PHP, one would have to perform such stripping explicitly.

```php
rtrim(file_get_contents('https://composer.github.io/installer.sig')))
    === hash_file('sha384', 'composer-setup.php'); // true
```

However, were `installer.sig` to only contain the signature and no other control characters, such as newlines, all versions of this code would work, including the shell script. I opine it is easier to use the signature file if it does not contain any formatting.

**Comment by Seldaek** [comment]
I don't mind removing the newline but I do wonder if it'll break anyone's code/automation at this point..

**Comment by Seldaek** [comment]
Did the change, let's hope it doesn't cause trouble.

**Comment by Bilge** [comment]
I guess this is the only way to find out.
